version: "3.4"

services:
  db:
    # https://docs.docker.com/desktop/mac/apple-silicon/#known-issues
    # Not all images are available for ARM64 architecture. 
    # You can add --platform linux/amd64 to run an Intel image under emulation. 
    # In particular, the mysql image is not available for ARM64. You can work around this issue by using a mariadb image.
    image: mariadb:10.5.8
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: test
    restart: always
  
  block_api:
    image: block_api
    ports: 
      - "8081:8081"
    env_file:
      - docker/config/.env
    depends_on:
      - db
    restart: always
